# Generated by Django 3.0.7 on 2020-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('post', models.TextField(verbose_name='Содержание статьи')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('poster', models.ImageField(upload_to='articles/', verbose_name='Постер')),
                ('url', models.SlugField(max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
