# Generated by Django 3.0.7 on 2020-07-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=1000, verbose_name='Занятие')),
                ('url', models.SlugField(blank=True, max_length=130, unique=True)),
            ],
            options={
                'verbose_name': 'Пробное занятие',
                'verbose_name_plural': 'Пробное занятие',
            },
        ),
        migrations.AlterModelOptions(
            name='trial',
            options={'verbose_name': 'Форма заполнения', 'verbose_name_plural': 'Форма заполнения'},
        ),
        migrations.AddField(
            model_name='trial',
            name='lesson',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Lesson', verbose_name='главное сообщение'),
            preserve_default=False,
        ),
    ]
